package com.dr.mandingo.projecteuler;

/**
 * Triangular, pentagonal, and hexagonal
 * 
 * ============================================================================
 * 
 * Triangle, pentagonal, and hexagonal numbers are generated by the following
 * formulae:
 * 
 * Triangle Tn=n(n+1)/2 1, 3, 6, 10, 15, ...
 * 
 * Pentagonal Pn=n(3n−1)/2 1, 5, 12, 22, 35, ...
 * 
 * Hexagonal Hn=n(2n−1) 1, 6, 15, 28, 45, ...
 * 
 * It can be verified that T285 = P165 = H143 = 40755.
 * 
 * Find the next triangle number that is also pentagonal and hexagonal.
 * 
 * Answer: 1533776805
 */
public class Problem045 {

	public static void main(String[] args) {
		int t = 285;
		int p = 165;
		int h = 143;
		long baseValue = 40755;
		long tValue = 0;
		long pValue = 0;
		long hValue = 0;
		while (true) {
			while (hValue < baseValue) {
				hValue = getHexagonal(++h);
				if (hValue >= baseValue) {
					baseValue = hValue;
					break;
				}
			}

			while (pValue < baseValue) {
				pValue = getPentagonal(++p);
				if (pValue >= baseValue) {
					baseValue = pValue;
					break;
				}
			}

			while (tValue < baseValue) {
				tValue = getTriangle(++t);
				if (tValue >= baseValue) {
					baseValue = tValue;
					break;
				}
			}
			if (hValue == pValue && pValue == tValue) {
				break;
			}
		}
		System.out.println("the answer is: " + baseValue);
	}

	public static long getTriangle(long n) {
		return (n * (n + 1)) / 2;
	}

	public static long getPentagonal(long n) {
		return (n * (3 * n - 1)) / 2;
	}

	public static long getHexagonal(long n) {
		return n * (2 * n - 1);
	}

}
